version: '3.1'

services:

  mongo:
    image: mongo:6.0.4-jammy
    restart: always
    # expose for compass and OLAP
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  sibyl2:
    image: williamfzc/sibyl2:v0.16.1
    restart: always
    ports:
      - "9876:9876"
    environment:
      SIBYL2_BINDING_DBTYPE: MONGO
      SIBYL2_BINDING_MONGO_DB_NAME: sibyl2
      SIBYL2_BINDING_MONGO_URI: mongodb://root:example@mongo:27017/

  metabase:
    image: metabase/metabase:v0.45.3
    restart: always
    ports:
      - "3000:3000"
